
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  model:
    build: ./models
    ports:
      - "5001:5000"
    depends_on:
      - backend

  # Add more model services as needed
